prevent cuda12 error
```
/usr/local/cuda/targets/x86_64-linux/include/cuda/std/__functional/invoke.h:460:127: error: static assertion failed: Attempt to use an extended __device__ lambda in a context that requires querying its return type in host code. Use a named function object, an extended __host__ __device__ lambda, cuda::proclaim_return_type, or an extended __device__ lambda with a trailing return type instead ([] __device__ (...) -> RETURN_TYPE {...}).
/usr/local/cuda/targets/x86_64-linux/include/cuda/std/__functional/invoke.h:460:127: note: '(((!(bool)__nv_extended_device_lambda_trait_helper<__nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > > >::value) || ((bool)__nv_extended_host_device_lambda_trait_helper<__nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > > >::value)) || ((bool)__nv_extended_device_lambda_with_trailing_return_trait_helper<__nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 15> > > >::value))' evaluates to false
/usr/local/cuda/targets/x86_64-linux/include/cuda/std/__functional/invoke.h: In instantiation of 'struct cuda::std::__4::__invoke_of<__nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, long int>':
/usr/local/cuda/targets/x86_64-linux/include/cuda/std/__functional/invoke.h:529:49:   required from 'struct cuda::std::__4::invoke_result<__nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, long int>'
/usr/local/cuda/targets/x86_64-linux/include/cub/device/device_reduce.cuh:988:143:   required from 'static cudaError_t cub::CUB_200500_800_860_NS::DeviceReduce::TransformReduce(void*, size_t&, InputIteratorT, OutputIteratorT, NumItemsT, ReductionOpT, TransformOpT, T, cudaStream_t) [with InputIteratorT = boost::multi::range<long int, long int, std::plus<>, std::minus<> >::const_iterator; OutputIteratorT = double*; ReductionOpT = std::plus<>; TransformOpT = __nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >; T = double; NumItemsT = int; cudaError_t = cudaError; size_t = long unsigned int; cudaStream_t = CUstream_st*]'
/usr/local/cuda/targets/x86_64-linux/include/thrust/system/cuda/detail/transform_reduce.h:81:229:   required from 'T thrust::THRUST_200500_800_860_NS::cuda_cub::detail::transform_reduce_n_impl(thrust::THRUST_200500_800_860_NS::cuda_cub::execution_policy<Sys1>&, InputIt, Size, UnaryOp, T, BinaryOp) [with Derived = thrust::THRUST_200500_800_860_NS::cuda_cub::par_t; InputIt = boost::multi::range<long int, long int, std::plus<>, std::minus<> >::const_iterator; Size = long int; UnaryOp = __nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >; T = double; BinaryOp = std::plus<>]'
/usr/local/cuda/targets/x86_64-linux/include/thrust/system/cuda/detail/transform_reduce.h:137:41:   required from 'T thrust::THRUST_200500_800_860_NS::cuda_cub::transform_reduce(execution_policy<Sys1>&, InputIt, InputIt, TransformOp, T, ReduceOp) [with Derived = par_t; InputIt = boost::multi::range<long int, long int, std::plus<>, std::minus<> >::const_iterator; TransformOp = __nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >; T = double; ReduceOp = std::plus<>]'
/usr/local/cuda/targets/x86_64-linux/include/thrust/detail/transform_reduce.inl:50:24:   required from 'OutputType thrust::THRUST_200500_800_860_NS::transform_reduce(const detail::execution_policy_base<DerivedPolicy>&, InputIterator, InputIterator, UnaryFunction, OutputType, BinaryFunction) [with DerivedPolicy = cuda_cub::par_t; InputIterator = boost::multi::range<long int, long int, std::plus<>, std::minus<> >::const_iterator; UnaryFunction = __nv_dl_wrapper_t<__nv_dl_tag<double (*)(const gpu::reduce&, const gpu::reduce&, const gpu::reduce&, double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >), gpu::run<double, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >, 1>, const long int, const long int, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> > >; OutputType = double; BinaryFunction = std::plus<>]'
/builds/correaa/boost-mpi3/inq/external_libs/gpurun/include/gpu/reduce.hpp:121:32:   required from 'Type gpu::run(const reduce&, const reduce&, const reduce&, Type, KernelType) [with Type = double; KernelType = __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), CATCH2_INTERNAL_TEST_15, 16> >]'
/builds/correaa/boost-mpi3/inq/external_libs/gpurun/include/gpu/reduce.hpp:437:20:   required from here
```

full log: https://gitlab.com/correaa/boost-mpi3/-/jobs/11905047314